### ISSUE TITLE
Issue of deprecated method `getParcelable`

### ISSUE THREAD

**Issue by Vaishakhi2000** [rilling/OpenTracks-Concordia#135]
## Describe the technical debt
The code analysis tool SonarQube has reported a code smell regarding deprecated method `getParcelable`
Please update the method according solutions.

## Type of technical debt
Code Smell 

## Location
src/main/java/de/dennisguse/opentracks/fragments/StatisticsRecordedFragment.java

## To Reproduce

Code Fragment:
<img width="871" alt="Screenshot 2023-02-04 at 11 21 59 PM" src="https://user-images.githubusercontent.com/75517257/216801540-94dfc7a8-5f49-4024-b60d-43817194a437.png">

Code Smell in Sonarqube:
<img width="987" alt="Screenshot 2023-02-04 at 11 21 17 PM" src="https://user-images.githubusercontent.com/75517257/216801517-7d5d504f-c247-4ad0-aa56-4a2c7171109f.png">

Expected Solution
need to check latest android document to substitute deprecated method with updated method.

**Comment by mit-27** [comment]
Changes implemented as part of original request.
