### ISSUE TITLE
Complete the task associated with this TODO comment. "TODO Pace won't work for now"

### ISSUE THREAD

**Issue by anahitaj** [rilling/OpenTracks-Concordia#198]
**Describe the technical debt**
Complete the task associated with this TODO comment. "TODO Pace won't work for now"

**Type of technical debt**
1. Complete the task, Code Smell, To do comment.
**Location**
[src/main/java/de/dennisguse/opentracks/viewmodels/GenericStatisticsViewHolder.java](https://github.com/rilling/OpenTracks-Concordia/blob/a5f4ab4d4e1fea40d32367e36f015d9e108df317/src/main/java/de/dennisguse/opentracks/viewmodels/GenericStatisticsViewHolder.java#L31)
**To Reproduce**

![1](https://user-images.githubusercontent.com/113778249/216849134-f906999d-d8aa-4921-a5b2-f468a680d435.png)

If applicable:
* add screenshots
* add logcat output

**Expected Solution**
 - OpenTracks version: [e.g. v3.2.4]
 - Expected Resolution : 
```
import java.text.DecimalFormat;

public class GenericStatisticsViewHolder extends RecyclerView.ViewHolder {

    private final TextView paceTextView;
    private final DecimalFormat paceFormat = new DecimalFormat("0.0");

    public GenericStatisticsViewHolder(@NonNull View itemView) {
        super(itemView);
        paceTextView = itemView.findViewById(R.id.pace_text_view);
    }

    public void bind(Statistics statistics) {
        // Other existing code

        double pace = statistics.getDuration() / (statistics.getDistance() / 1000);
        paceTextView.setText(paceFormat.format(pace) + " min/km");
    }
}
```

**Comment by ballista01** [comment]
TODO solved, close issue
