### ISSUE TITLE
Adding comments and handling exceptions for Non-compliant code

### ISSUE THREAD

**Issue by anuragagarwal6895** [rilling/OpenTracks-Concordia#202]
**Describe the technical debt**
Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation.

**Type of technical debt**
Critical Code Smell

**Location**
/src/main/java/de/dennisguse/opentracks/settings/SettingsCustomLayoutListActivity.java

**To Reproduce**

_Screenshot from Sonarqube_

<img width="1335" alt="Screenshot 2023-02-06 at 1 05 26 AM" src="https://user-images.githubusercontent.com/117996954/216897106-620ee35a-0129-4860-9aef-bfca054f04a8.png">

_Screenshot from Code_

<img width="979" alt="Screenshot 2023-02-06 at 1 11 00 AM" src="https://user-images.githubusercontent.com/117996954/216896619-27cd085e-7fea-4a03-bce3-022898ce0193.png">

**Expected Solution**
 Add **comment** explaining the reason for blank Method. Add **Exception**.

**Comment by RancyKaur** [comment]
Closing
