### ISSUE TITLE
Adding comments and handling exceptions for Non-compliant code

### ISSUE THREAD

**Issue by anuragagarwal6895** [rilling/OpenTracks-Concordia#203]
**Describe the technical debt**
Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation.

**Type of technical debt**
Critical Code Smell

**Location**
/src/main/java/de/dennisguse/opentracks/settings/SettingsCustomLayoutListActivity.java

**To Reproduce**

_Screenshot from Sonarqube_

<img width="1324" alt="Screenshot 2023-02-06 at 1 18 18 AM" src="https://user-images.githubusercontent.com/117996954/216898469-ccf9970f-9bb7-4840-ab38-c73ec3ad14ba.png">

_Screenshot from Code_

<img width="993" alt="Screenshot 2023-02-06 at 1 19 18 AM" src="https://user-images.githubusercontent.com/117996954/216898551-3f41d536-0bc9-4107-af14-12bcbdbfa8fb.png">

**Expected Solution**
 Add **comment** explaining the reason for blank Method. Add **Exception**.

**Comment by RancyKaur** [comment]
Closing
