### ISSUE TITLE
Rename "fragment" which hides the field declared

### ISSUE THREAD

**Issue by SharanyaAkkenapally** [rilling/OpenTracks-Concordia#209]
Describe the technical debt
Rename "fragment" which hides the field declared. Field named 'fragment' of same type PreferenceFragmentCompat is define at class and method level.

Type of technical debt
CodeSmell

Location/Path:
[OpenTracks-Concordia/SettingsActivity.java at main · rilling/OpenTracks-Concordia (github.com)](https://github.com/rilling/OpenTracks-Concordia/blob/main/src/main/java/de/dennisguse/opentracks/settings/SettingsActivity.java)

Steps to Reproduce
 
![WhatsApp Image 2023-02-06 at 9 43 13 AM](https://user-images.githubusercontent.com/65612137/217065616-76e924d6-3107-4bcf-8cf2-7b32032e614e.jpeg)
![WhatsApp Image 2023-02-06 at 9 43 18 AM](https://user-images.githubusercontent.com/65612137/217065668-9828e763-a336-4180-9646-5ae44725d1f8.jpeg)

 

 

Expected Solution 
OpenTracks version:  v3.3.1 
The shown local variable can be renamed with a new name thus overriding or shadowing conflict is resolved.

**Comment by RancyKaur** [comment]
Closing
