### ISSUE TITLE
Overriding methods should do more than simply call the same method in the super class

### ISSUE THREAD

**Issue by joyal7701** [rilling/OpenTracks-Concordia#23]
**Describe the technical debt**
Overriding a method just to call the same method from the super class without performing any other actions is useless and misleading.

**Type of technical debt**
Code debt

**Location**
src/main/java/de/dennisguse/opentracks/introduction/WelcomeFragment.java
![WhatsApp Image 2023-02-02 at 14 39 38](https://user-images.githubusercontent.com/63547847/216445311-86850ab9-9ac5-4fed-8bed-38dd4e412b6b.jpg)

**To Reproduce**
![image](https://user-images.githubusercontent.com/63547847/216447969-3055a025-cb01-41c8-a47f-cd7ef20dcc94.png)

**Expected Solution**
 - Remove onCreate method to simply inherit it.

**Comment by joyal7701** [comment]
![WhatsApp Image 2023-02-04 at 14 01 22](https://user-images.githubusercontent.com/63547847/216784941-4e098081-aecb-4b36-b874-145066a37d18.jpg)

**Comment by joyal7701** [comment]
![WhatsApp Image 2023-02-04 at 14 01 22](https://user-images.githubusercontent.com/63547847/216785073-6465e0c9-b1cc-447c-9c9c-09b712465522.jpg)

**Comment by yusufkhan07** [comment]
I had to delete your commits because the build was failing (Not necessarily because of your commit but I had to delete all commits from the last 1 hour). Please commit your changes to the main branch again and make sure build is working before committing.
