### ISSUE TITLE
Adding a visualization of the last Track on the Stats tab

### ISSUE THREAD

**Issue by rilling** [rilling/OpenTracks-Concordia#232]
**Is your feature request related to a problem? Please describe.**
This is a feature request - to have a small map of the track included in the app. The bottom part could display a map highlighting the recorded route.

**Describe the solution you'd like**
Given is the following Stats screen:

![Screenshot_20230207-153237](https://user-images.githubusercontent.com/1248571/217362119-25b8499b-c58d-4504-aa3e-08384343bb4a.png)

The font could be reduce slightly to create some more space. But there is sufficient space to provide a small map of the current track recorded. Similar to 
![Screenshot_20230130-184822](https://user-images.githubusercontent.com/1248571/217366871-38f61b02-f212-4437-aaab-9e29fc8a29e2.png)

**Describe alternatives you've considered**
The map could be on the top, but I believe the placement of the map at the bottom would keep the UI design more consistent.

**Comment by lakshyakalia** [comment]
This issue has been completed. Please refer to Pull Request  #304.
