### ISSUE TITLE
Exporting/importing Trackdata to/from an external drive (e.g., Onedrive)

### ISSUE THREAD

**Issue by rilling** [rilling/OpenTracks-Concordia#243]
**Is your feature request related to a problem? Please describe.**
Currently the tool only supports to import/export track data to a local folder on the phone

**Describe the solution you'd like**
Have the option to import/export track data from an external folder (drive) - e.g., Onedrive
1. Create a folder based on the profile name (you will have to communicate with the group which is maintaining the profile part)
2. Replicate the folder structure to be the same as currently used for the the local import/export - only the target will now be a one drive and these folders will be nested within the profile name folder 

Below is an example of a onedrive folder - should work
https://1drv.ms/u/s!ArPyXNcsMbKOhb4d0eB2kyDoib3mew?e=ZuXxML

**Describe alternatives you've considered**
No need for FTP or other webserver.

**Additional context**
Ideally this will allow later on to provide additional features such a leader board... but not part of this issue right now.

**Comment by jigar944** [comment]
#254

**Comment by jigar944** [comment]
eeb327212136a8a443775b68e1e7468e195b27b4

**Comment by jigar944** [comment]
PR: 3a93bd44f614c4e3051acf823acca60a4c5aa05d

**Comment by jigar944** [comment]
Brainstorming on connecting Onedrive with android app

**Comment by Shefali-Upadhyaya** [comment]
As discussed with the professor, we will not be using OneDrive instead will try to use any local server where files and folders can be imported/exported without signing in.

**Comment by jigar944** [comment]
I have added the import and Export feature in the android app.

**Comment by jigar944** [comment]
Now, we need to work on creating a user directory for all new users on the cloud and save their data individually to their folder.

**Comment by jigar944** [comment]
![image](https://user-images.githubusercontent.com/40587572/231276513-dfd51e14-8ba7-42f6-966b-55bf325dedb7.png)
The GCP console and folder created based on user profile. so whenever they do import/export, it will be imported/exported to/from a specific user folder.

**Comment by jigar944** [comment]
![image](https://user-images.githubusercontent.com/40587572/231277068-714ae889-3c8c-45e0-b419-e4df80f0dde1.png)
Here, options for import and export to/from the drive are added.

**Comment by Shefali-Upadhyaya** [comment]
Code fix has been merged with the main branch.
