### ISSUE TITLE
Add an entry to the Profile page in the buttom dropdown menu

### ISSUE THREAD

**Issue by ballista01** [rilling/OpenTracks-Concordia#247]
**Is your feature request related to a problem? Please describe.**
Sub issue of https://github.com/rilling/OpenTracks-Concordia/issues/5

**Describe the solution you'd like**
Add an entry to the Profile page in the buttom dropdown menu

**Describe alternatives you've considered**
A dedicated profile button in the button app bar (but not necessary)

**Additional context**
https://github.com/rilling/OpenTracks-Concordia/issues/5

**Comment by whonamra** [comment]
Implemented profile page entry in the button dropdown menu.
