### ISSUE TITLE
Create Weather APIs for fetching the weather data

### ISSUE THREAD

**Issue by saloni213** [rilling/OpenTracks-Concordia#249]
**Is your feature request related to a problem? Please describe.**
Sub-task issue for enhancement #236 
The application must collect the current weather data for the location to display it to the user on the Stats (Summary) page.

**Describe the solution you'd like**
The solution is to integrate OpenWeatherMap API into the application that can provide the weather data like temperature, wind speed, humidity, etc. for the current location. The API is reliable, accurate, and easy to use, with clear documentation and guidelines for integration. The API is also compatible with the application's framework.

Architecture Screenshot:
![Weather](https://user-images.githubusercontent.com/60805187/225955338-0f2c4823-c18c-4577-a65e-1b0849b57a49.jpeg)

**Describe alternatives you've considered**
One alternative would be to use a web scraping technique to extract the temperature data from a weather website. However, this approach is not recommended as it can be unreliable, prone to errors, and may violate the terms of use of the website. Another alternative would be to use a different weather API, but this may require significant changes to the application code and may not be as accurate or reliable as the preferred API.

**Additional context**
https://openweathermap.org/
https://openweathermap.org/appid#:~:text=Once%20you%20sign%20up%20using,technical%20information%20for%20each%20product.

**Comment by nishantarora23** [comment]
The OpenTracks-Concordia has been integrated with the OpenWeatherMap.
