### ISSUE TITLE
Create a model function for Pressure & Humidity for Weather Data in Model

### ISSUE THREAD

**Issue by nandinibibra-96** [rilling/OpenTracks-Concordia#263]
Is your feature request related to a problem? Please describe.
This issue is a sub-task for issue https://github.com/rilling/OpenTracks-Concordia/issues/255

Describe the solution you'd like
Create getters & setters for Pressure & Humidity 

Describe alternatives you've considered
The solution will be intact with other models in /data/models

**Comment by supradeepdanturti** [comment]
Created getters & setters for Pressure & Humidity under #d39d475 commit

**Comment by supradeepdanturti** [comment]
Fixed the issue in commit d39d475 https://github.com/rilling/OpenTracks-Concordia/commit/2335bd515dc88cb2316fea9b7874783f2303f283
