### ISSUE TITLE
Adding a Formula for computing calories - Conversion of Calories

### ISSUE THREAD

**Issue by nandinibibra-96** [rilling/OpenTracks-Concordia#274]
Is your feature request related to a problem? Please describe.
Sub Task for - https://github.com/rilling/OpenTracks-Concordia/issues/6
data/models is adding new field Calories to the model. We need to create a function that will be used to compute Calories based on Distance, Speed etc metrics that are available in OpenTracks. This utility function will focus specifically on conversion of Calories.

Describe the solution you'd like
Please refer to the original task.

Describe alternatives you've considered
There are no particular alternatives, the team can create algorithm/formulas as deemed fine.

**Comment by plsakr** [comment]
This issue was resolved in the commit e00b8b164dadec52671199866e242ae62e99eca7
