### ISSUE TITLE
Create function to calculate Calories 

### ISSUE THREAD

**Issue by shashank6341** [rilling/OpenTracks-Concordia#279]
**Is your feature request related to a problem? Please describe.**
Group 9 is implementing a feature enhancement related to Calories. We need to collaborate with Team 7 to implement a method that calculates Calories based on the existing data like Distance, Time and Heart Rate.

**Describe the solution you'd like**
Create a method that calculates Calories based on the existing data like Distance, Time and Heart Rate.

**Describe alternatives you've considered**
There a different formulas available on how to calculate the calories burnt per work out - depending on the type of exercise. The challenge is to come up with some adjustment factors, since not all the information might be readily available. E.g., power generated during the exercise, heart rate might be missing. However, we do have factors such as speed, duration and exercise type.

**Additional context**
Link to the original Feature Enhancement:
https://github.com/rilling/OpenTracks-Concordia/issues/6

**Comment by Driven2Develop** [comment]
hello @shashank6341 

If you need the calorie count displayed as part of the statistics model please let us know. You may have a dependency on **ui/intervals** and we can assist if you create a subtask for G4

**Comment by shashank6341** [comment]
Hi, We do not want to display it as part of the statistics model but want a method to calculate the calories. 

I will also check the dependency on ui/intervals once and create a subtask for G4 and confirm back to you.
