### ISSUE TITLE
 Add "Weight" field to user profile

### ISSUE THREAD

**Issue by anahitaj** [rilling/OpenTracks-Concordia#305]
Description: It would be useful to have a "Weight" field in the user's profile where users can enter their current weight. This information could be used to provide more accurate tracking of calories burned during activities, making the app more useful for those who are tracking their fitness and weight loss progress.
Reference to the main issue: This feature request would add a new field to the user's profile, improving the overall user experience of OpenTracks-Concordia. #5 
Labels: feature request, user profile, weight tracking #5 #G19

**Comment by whonamra** [comment]
The height and weight fields are added to user profile, henceforth this issue has been closed.
