### ISSUE TITLE
Add "Height" field to user profile

### ISSUE THREAD

**Issue by NithinHarikrishnan** [rilling/OpenTracks-Concordia#319]
Description: Having a "Height" section in the user's profile would be advantageous as it would allow users to input their present height. This data could be utilized to enhance the precision of calculating calories burned during physical activities, thereby increasing the app's usefulness for individuals who are monitoring their fitness and height reduction progress.
Reference to the main issue: This feature request would add a new field to the user's profile, improving the overall user experience of OpenTracks-Concordia. https://github.com/rilling/OpenTracks-Concordia/issues/5
Labels: feature request, user profile, height tracking https://github.com/rilling/OpenTracks-Concordia/issues/5 #G19

**Comment by NithinHarikrishnan** [comment]
Description: Having a "Height" section in the user's profile would be advantageous as it would allow users to input their present height. This data could be utilized to enhance the precision of calculating calories burned during physical activities, thereby increasing the app's usefulness for individuals who are monitoring their fitness and height reduction progress.
Reference to the main issue: This feature request would add a new field to the user's profile, improving the overall user experience of OpenTracks-Concordia. https://github.com/rilling/OpenTracks-Concordia/issues/5
Labels: feature request, user profile, height tracking https://github.com/rilling/OpenTracks-Concordia/issues/5 #G19

**Comment by whonamra** [comment]
The height Field is also added alongside the Weight field. This issue is henceforth closed.
