### ISSUE TITLE
Add utility methods to EGM2008Utils class for calculating geoid undulation corrections

### ISSUE THREAD

**Issue by dhhruv** [rilling/OpenTracks-Concordia#344]
**Is your feature request related to a problem? Please describe.**
Currently, the EGM2008Utils class in OpenTracks provides a method for creating corrections for the EGM2008 geoid model based on a given location. However, there is no straightforward way to calculate the latitude and longitude indices or the undulation correction for a given set of coordinates using the class. This makes it difficult for other parts of the application to utilize the EGM2008 geoid model.

**Describe the solution you'd like**
To address this issue, I propose adding utility methods to the EGM2008Utils class that allow for calculating the latitude and longitude indices for a given location, and for retrieving the undulation correction at a specific index in the EGM2008 data. Specifically, I have added the following functions:

- **getLatitudeIndex(Location location)**: Returns the latitude index corresponding to the given location, based on the EGM2008 dataset.
- **getLongitudeIndex(Location location)**: Returns the longitude index corresponding to the given location, based on the EGM2008 dataset.
- **getLatitudeLongitude(@NonNull Location location)**: Returns the latitude and longitude of the location for which the correction is being applied.
- **getUndulationCorrection(DataInputStream dataInputStream, int latitudeIndex, int longitudeIndex)**: Calculates the undulation correction for a given latitude and longitude index using the EGM2008 data.

With these new utility methods, other parts of the application can more easily utilize the EGM2008 geoid model to correct altitude values for a given location. These functions will be useful for any application that requires accurate altitude measurements, such as mapping applications or outdoor activity trackers.

**Describe alternatives you've considered**
One alternative would be to create a separate class that handles calculations related to the EGM2008 geoid model, rather than adding these methods to the EGM2008Utils class. However, I believe that adding the methods to the existing class makes more sense, as they are closely related to the existing functionality of the class.

**Additional context**
I have already implemented the proposed functions in the EGM2008Utils class and have tested them thoroughly. I believe that these functions will be useful to other developers working on OpenTracks or any application that requires accurate altitude measurements.

**Comment by parth-5097** [comment]
Related changes are merged into #384
