### ISSUE TITLE
Add additional utility methods to FileUtils

### ISSUE THREAD

**Issue by dhhruv** [rilling/OpenTracks-Concordia#345]
**Is your feature request related to a problem? Please describe.**
The FileUtils class in OpenTracks currently lacks some important utility methods. Specifically, we need methods for copying a directory, generating unique file names, and deleting all files in a directory except for a specified list of files. These methods are necessary for various operations in the OpenTracks app, such as exporting tracks with associated photos.

**Describe the solution you'd like**
I propose adding the following utility methods to the FileUtils class:

- **copyDirectory(File srcDir, File dstDir):** This method should recursively copy a directory and its contents to a new location.
- **generateUniqueFileName(File directory, String baseName, String extension):** This method should generate a unique filename by appending a numeric suffix to the base filename.
- **deleteFilesExcept(File directory, List<File> exclusions):** This method should delete all files in a directory except for a specified list of files.

**Describe alternatives you've considered**
N/A

**Additional context**
The FileUtils class is a critical component of the OpenTracks app and is used in many places throughout the codebase. These new utility methods will improve the functionality and flexibility of the app, making it easier to manage and manipulate files.

**Comment by parth-5097** [comment]
Related changes merged into #384
