### ISSUE TITLE
Enhancements to IntentDashboardUtils.java: New Utility Functions for Track Filtering and Custom Dashboard Intent

### ISSUE THREAD

**Issue by dhhruv** [rilling/OpenTracks-Concordia#347]
**Is your feature request related to a problem? Please describe.**
The IntentDashboardUtils.java in the utils package currently lacks some utility functions that would make it easier to filter tracks by various criteria and create custom intents for starting the dashboard with additional configuration options. This makes it more challenging for developers to easily integrate these functionalities into their projects.

**Describe the solution you'd like**
I have implemented 4 new utility functions in IntentDashboardUtils.java that I would like to have added to the project:

- **showMultipleTracksOnMap():** Sends an intent to show multiple tracks on a map as resource URIs.
- **filterTracksByDistance():** Filters the given list of tracks by distance.
- **filterTracksByDate():** Filters the given list of tracks by date.
- **createCustomDashboardIntent():** Creates a custom intent to start a dashboard with additional configuration options.
These new functions will make it more convenient for developers to use the library and easily integrate the desired functionalities into their projects.

**Describe alternatives you've considered**
An alternative approach would be to implement these functions individually within each project that requires them. However, this would lead to code duplication and make it more difficult to maintain and update the code in the future.

**Additional context**
By adding these utility functions to IntentDashboardUtils.java, we can provide developers with a more comprehensive and versatile set of tools for working with tracks and dashboards. This will make the library more attractive and useful for developers, ultimately benefiting the community and fostering further development and collaboration.

**Comment by parth-5097** [comment]
Related changes are merged into #384
