### ISSUE TITLE
Fix computation of elevation gain/loss(Intervals Page)

### ISSUE THREAD

**Issue by sgurjeet** [rilling/OpenTracks-Concordia#351]
**Describe the bug**
The calculation of the elevation is complete off. The total elevation change should only be a few meters.

**To Reproduce**
1. Go to any track stats
2. Click on 'Intervals' tab
3. Notice elevation gain/loss values

Sub-task of: https://github.com/rilling/OpenTracks-Concordia/issues/4

**Comment by saurabhs679** [comment]
Fixed in [17cf3d9](https://github.com/rilling/OpenTracks-Concordia/commit/17cf3d91220ef215ab99d48c72970ab7922d8341)
