### ISSUE TITLE
Fix computation of elevation gain/loss(TrackRecorder)

### ISSUE THREAD

**Issue by sgurjeet** [rilling/OpenTracks-Concordia#352]
**Describe the bug**
The calculation of the elevation is complete off. The total elevation change should only be a few meters.

**To Reproduce**
1. Go to any track stats
2. Notice elevation gain/loss values in Stats or Intervals tab

Sub-task of: https://github.com/rilling/OpenTracks-Concordia/issues/4

**Comment by Het95** [comment]
Issue fixed by making changes in TrackRecordingManager.java

**Comment by Het95** [comment]
#495 
https://github.com/rilling/OpenTracks-Concordia/tree/feature-g10-fix-for-495
