### ISSUE TITLE
Document Detected by PMD

### ISSUE THREAD

**Issue by Driven2Develop** [rilling/OpenTracks-Concordia#362]
**Description**
A combination of minor semantic and code readability issues that once remedied will improve the overrall comprehension of the source code

**Type of technical debt**
Documentation

**Location**
~..\IntervalStatistics.java LINE:107

**Description**
Document empty constructor

**Comment by riddhibhuva** [comment]
fixed the issue 
Commit link :  
https://github.com/rilling/OpenTracks-Concordia/commit/5354352a25063fd8a988c78bea9b70a201c0f460
