### ISSUE TITLE
PMD design suggestion

### ISSUE THREAD

**Issue by Driven2Develop** [rilling/OpenTracks-Concordia#365]
**Description**
A combination of minor semantic and code readability issues that once remedied will improve the overrall comprehension of the source code

**Type of technical debt**
Design

**Location**
~\..\IntervalStatisticsModel.java LINE:37

**Description**
Perhaps ‘distanceInterval’ could be replaced by a local variable.

**Comment by vidhisagathiya** [comment]
solved by the [Commit- 489342f](https://github.com/rilling/OpenTracks-Concordia/commit/489342fa32054fd398190eb7ba13360d2e08cda5)
