### ISSUE TITLE
Computation of the elevation gain/loss is wrong

### ISSUE THREAD

**Issue by rilling** [rilling/OpenTracks-Concordia#4]
**Describe the bug**
The calculation of the elevation is complete off. The total elevation change should only be a few meters. 

**To Reproduce**
1. Import the attached GPX file for the specific workout (Please note: The file should be renamed from 2023-01-26_14_43_49.785_2023-01-26T14_43-05.txt => 2023-01-26_14_43_49.785_2023-01-26T14_43-05.gpx. The rename was necessary since GitHub does not allow attachments of the format .gpx

[2023-01-26_14_43_49.785_2023-01-26T14_43-05.txt](https://github.com/rilling/OpenTracks-Concordia/files/10541590/2023-01-26_14_43_49.785_2023-01-26T14_43-05.txt)

3. Display the workout - the result should like as the attached screen capture. Over 4000 meter gain is unrealistic 
 

![OpenTraceStatOverview](https://user-images.githubusercontent.com/1248571/215635879-a12c4f79-0a60-473c-bcba-4d800c079a1d.png)

![Screenshot_20230130-184632](https://user-images.githubusercontent.com/1248571/215636933-d2f32cfe-d899-4c82-8fdd-d2d9f3ad7609.png)

A more reasonable result from a different tracking program is provided.

![Screenshot_20230130-184837](https://user-images.githubusercontent.com/1248571/215636392-219599cf-dd1a-4655-8929-2950282ee4e3.png)

To see the correct elevation is press "By Time" Tab on the top of the screen. You will see that there are only marginal elevation changes during the duration of the track. Noise from the elevation data should be removed.

**Comment by AntasJain** [comment]
I have written a solution for this issue and issue #235  being part of Group 20, I was looking for a solution in Sensors component but I deviced a solution in stats/TrackStatistics.java where I am putting value of totalGain and totalLoss as the highest value for the particular interval, I am going to commit the same as part of deliverable 3, here 
![Screenshot_20230417_174449](https://user-images.githubusercontent.com/68066464/232617773-d14f3587-85d5-4af4-84c4-112b7582b221.png)
are screenshot for the same solution's result:
![Screenshot_20230417_161931](https://user-images.githubusercontent.com/68066464/232617638-f94af3af-4c1b-4161-802c-b1a8bfec3ca6.jpg)

**Comment by AntasJain** [comment]
Closing the issue
