### ISSUE TITLE
Add Date Picker for field birthdate in User's Profile Settings page.

### ISSUE THREAD

**Issue by whonamra** [rilling/OpenTracks-Concordia#407]
**Is your feature request related to a problem? Please describe.**
There is no date picker for the birth date field on User's Profile Settings page.

**Describe the solution you'd like**
Provide implementation for picking dates from the usual date picker, which can choose dates, months, and years.

**Describe alternatives you've considered**
We considered a simple text field. However, it could have been more user-friendly so we went ahead with the date picker from Android library.

**Additional context**
No as such.

**Feature request group**
Group No: 19

**Related Feature/issue**
#5 #247

**Comment by Gurpreet240797** [comment]
Changes are working fine. Hence Closing the issue.
