### ISSUE TITLE
Add Height text input field in User's Profile Settings page. 

### ISSUE THREAD

**Issue by whonamra** [rilling/OpenTracks-Concordia#408]
**Is your feature request related to a problem? Please describe.**
There is no input text field for the Height field on User's Profile Settings page.

**Describe the solution you'd like**
Provide implementation for the input of Height. 

**Describe alternatives you've considered**
We considered only a simple text field.

**Feature request group**
Group No: 19

**Related Feature/issue**
#5

**Comment by ballista01** [comment]
Issue branch: https://github.com/rilling/OpenTracks-Concordia/tree/Issue%23408-ProfileHeightField

**Comment by ballista01** [comment]
Commit: https://github.com/rilling/OpenTracks-Concordia/commit/53ac6bd270d4ad04962939293552fee4fc870cee

**Comment by whonamra** [comment]
Successfully implemented.
