### ISSUE TITLE
Use isEmpty() to check whether the collection is empty or not.

### ISSUE THREAD

**Issue by Anagha630** [rilling/OpenTracks-Concordia#431]
**Describe the technical debt**
Substitute calls to size() == 0 (or size() != 0, size() > 0, size() < 1) with calls to isEmpty()

**Type of technical debt**
Code Smell

**Location**
src/main/java/de/dennisguse/opentracks/chart/ChartView.java

![image](https://user-images.githubusercontent.com/62924509/232286689-d0b31d3b-fb29-4007-a93a-e53f28e51700.png)

**Expected Solution**
 - OpenTracks version: [e.g. v3.2.4]
 - Expected Resolution : 
 Replace  chartPoints.size() > 0 with !chartPoints.isEmpty()

**Comment by Madhava5** [comment]
Replaced the chartPoints.size()>0 with !chartPoints.isEmpty()
