### ISSUE TITLE
Add the missing @deprecated Javadoc tag.

### ISSUE THREAD

**Issue by Anagha630** [rilling/OpenTracks-Concordia#432]
**Describe the technical debt**
Javadoc representation is incomplete and is resulting in a code smell. Hence tag should be added.

**Type of technical debt**
Code smell

**Location**
src/main/java/de/dennisguse/opentracks/chart/ChartFragment.java

**To Reproduce**

1. Copy paste the code fragment which contains the technical debt.

![image](https://user-images.githubusercontent.com/62924509/232286827-06cfd2e7-ae64-4bda-8a08-d4d0bea668ec.png)

**Expected Solution**
 - OpenTracks version: [e.g. v3.2.4]
 - Expected Resolution : Add @deprecated Javadoc tag for the method isSelectedTrackRecording()

**Comment by CHAB5** [comment]
<img width="1171" alt="Screenshot 2023-04-17 at 9 30 02 PM" src="https://user-images.githubusercontent.com/100051530/232660709-cda881d1-626f-4c17-80c5-a60e7bb239d3.png">
