### ISSUE TITLE
Extra pair of parentheses

### ISSUE THREAD

**Issue by Anagha630** [rilling/OpenTracks-Concordia#434]
**Describe the technical debt**
Extra parentheses makes the code unnecessarily complex to read. One of which exists in line 774 of ChartView.java file.

**Type of technical debt**
Code smell

**Location**
src\main\java\de\dennisguse\opentracks\chart\ChartView.java

**To Reproduce**

1. Copy paste the code fragment which contains the technical debt.

![image](https://user-images.githubusercontent.com/62924509/232287484-2f030ca2-32be-43fb-941b-bce77dce0f8e.png)

**Expected Solution**
 - OpenTracks version: [e.g. v3.2.4]
 - Expected Resolution : Remove the extra pair of parentheses

**Comment by tylrishabh** [comment]
https://github.com/rilling/OpenTracks-Concordia/commit/49915ba01e650a99125a4b169ba41d436a09cd6d
![image](https://user-images.githubusercontent.com/32161592/232334508-3e263beb-ca74-4ee7-8583-70cc9f5880a0.png)
