### ISSUE TITLE
Simplify Boolean Returns

### ISSUE THREAD

**Issue by Anagha630** [rilling/OpenTracks-Concordia#435]
**Describe the technical debt**
Unnecessary if conditions can be avoided by using boolean operations. One such improvement can be done in ChartView.java file.

**Type of technical debt**
Code smell

**Location**
\src\main\java\de\dennisguse\opentracks\chart\ChartView.java

**To Reproduce**

1. Copy paste the code fragment which contains the technical debt.

![image](https://user-images.githubusercontent.com/62924509/232287608-77ec37c4-6340-4062-b1f9-87b3fb9c19bf.png)

**Expected Solution**
 - OpenTracks version: [e.g. v3.2.4]
 - Expected Resolution : This if statement can be replaced by `return !{condition} || {elseBranch};`

**Comment by Madhava5** [comment]
replaced if statement with return !{condition}
