### ISSUE TITLE
Move fling() method into the anonymous class 

### ISSUE THREAD

**Issue by Anagha630** [rilling/OpenTracks-Concordia#436]
**Describe the technical debt**
Method fling() is being called by onFling() method that exists within the anonymous call. Moving method fling() into the anonymous class will help it easy to locate and prevents code smell.

**Type of technical debt**
Code smell

**Location**
src/main/java/de/dennisguse/opentracks/chart/ChartView.java

**To Reproduce**

1. Copy paste the code fragment which contains the technical debt.

![image](https://user-images.githubusercontent.com/62924509/232288089-53a3a20d-606a-4098-bce2-89b1526b7d1f.png)

**Expected Solution**
 - OpenTracks version: [e.g. v3.2.4]
 - Expected Resolution : Move method fling() into the anonymous class declared at line 124 of ChartView.java file

**Comment by tanzia-ahmed** [comment]
Resolved:

https://github.com/rilling/OpenTracks-Concordia/commit/3043b60ecc5f7820d2d6fb3414ddfd34b173e836
