### ISSUE TITLE
Remove unused variables in BluetoothUtils.java

### ISSUE THREAD

**Issue by firasrashidi** [rilling/OpenTracks-Concordia#460]
**Describe the technical debt**
There exists unused variables hanging around in teh code that need to be removed

**Type of technical debt**
Code debt where there is unused code that can come in as confusing to developers

**Location**
BluetoothUtils.java

**To Reproduce**

![image](https://user-images.githubusercontent.com/36714331/232339668-3091f128-e665-4e45-af8c-692714872ac4.png)

**Expected Solution**
 - Remove such unused variables with the help of the detection software in SonarQube

**Comment by bajwa96** [comment]
Please find the issue here https://github.com/OpenTracksApp/OpenTracks/commit/e01e1bc3ddc65fee95b499cf5b0deef300cd0f2d

**Comment by bajwa96** [comment]
The issue has been resolved

**Comment by bajwa96** [comment]
<img width="1331" alt="Screenshot 2023-04-16 at 4 23 27 PM" src="https://user-images.githubusercontent.com/16022534/232340050-d43fa34c-5ce4-47f1-96a2-727c1e4ba1e5.png">
