### ISSUE TITLE
Parameter 2 to this call is marked "@NonNull" but null could be passed

### ISSUE THREAD

**Issue by bajwa96** [rilling/OpenTracks-Concordia#462]
"@Non Null" values should not be set to null java:S2637A clear and concise description of the technical debt.

Values could be potentially be null due to any reason which could result in exception/error in future

src/…./java/de/dennisguse/opentracks/util/ExportUtils.java

**To Reproduce**

<img width="958" alt="Screenshot 2023-04-16 at 4 26 56 PM" src="https://user-images.githubusercontent.com/16022534/232340243-bb71fbf4-f583-48b3-91f8-39d0347ffc5e.png">

Use if null check to resolve this issue

**Comment by karmakarvishal** [comment]
The issue is resolved.
The link to the commit is: https://github.com/OpenTracksApp/OpenTracks/commit/0b7e5e0bb32d6d56fb2e3b40854194f66932ada9
