### ISSUE TITLE
Use try-with-resources or close this "OutoutStream" in a "finally! clause

### ISSUE THREAD

**Issue by bajwa96** [rilling/OpenTracks-Concordia#463]
Resources should be closed, for instance if one process is accessing the file and another tries to access the same it could result in error or deadlock which should be avoided at all costs

src/…./java/de/dennisguse/opentracks/util/ExportUtils.java

<img width="937" alt="Screenshot 2023-04-16 at 4 28 44 PM" src="https://user-images.githubusercontent.com/16022534/232340320-7d5420e4-9c07-4fd1-b805-f4b4b7287429.png">

Use finally block to close the output stream

**Comment by sahrawatvinay** [comment]
I have fixed this issue using try-with-resources.
For reference : https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
