### ISSUE TITLE
PMD: System Utils class has only private constructors and should be final.

### ISSUE THREAD

**Issue by whonamra** [rilling/OpenTracks-Concordia#467]
**Describe the technical debt**
System Utility class has only private constructor and it should be final

**Type of technical debt**
Code Smell.

**Location**
/src/main/java/de/dennisguse/opentracks/util/SystemUtils.java:37

**To Reproduce**

```
public class SystemUtils {

    private static final String TAG = SystemUtils.class.getSimpleName();

    private SystemUtils() {
    }
```

**Expected Solution**
Making System Utils class final.

**Comment by Gurpreet240797** [comment]
Successfully made changes to the issue.

**Comment by Gurpreet240797** [comment]
Closing the ticket after testing.
