### ISSUE TITLE
PMD: UnusedPrivateField. Need to avoid unused private fields such as 'TAG'.

### ISSUE THREAD

**Issue by whonamra** [rilling/OpenTracks-Concordia#470]
**Describe the technical debt**
UnusedPrivateField. Need to avoid unused private fields such as 'TAG'.

**Type of technical debt**
Code Smell.

**Location**
/src/main/java/de/dennisguse/opentracks/util/LocationUtils.java:29

**To Reproduce**

```
public class LocationUtils {

    private static final String TAG = LocationUtils.class.getSimpleName();

    private LocationUtils() {
    }
```

**Expected Solution**
Removing final TAG variable.

**Comment by anahitaj** [comment]
fixed the issue
