### ISSUE TITLE
PMD: UnusedPrivateField. Need to avoid unused private fields such as 'JPEG_EXTENSION'.

### ISSUE THREAD

**Issue by whonamra** [rilling/OpenTracks-Concordia#471]
**Describe the technical debt**
UnusedPrivateField. Need to avoid unused private fields such as 'JPEG_EXTENSION'.

**Type of technical debt**
Code Smell.

**Location**
/src/main/java/de/dennisguse/opentracks/util/IntentUtils.java:38

**To Reproduce**

```
public class IntentUtils {

    private static final String TAG = IntentUtils.class.getSimpleName();

    private static final String JPEG_EXTENSION = "jpeg";

    private IntentUtils() {
    }
```

**Expected Solution**
Removing final JPEG_EXTENSION variable.

**Comment by harika89** [comment]
Unused private variable JPEG_EXTENSION has been removed.

**Comment by harika89** [comment]
After resolving the issue:

`public class IntentUtils {

    private static final String TAG = IntentUtils.class.getSimpleName();

    private IntentUtils() {
    }`

**Comment by harika89** [comment]
After resolving the issue:

`public class IntentUtils {

    private static final String TAG = IntentUtils.class.getSimpleName();

    private IntentUtils() {
    }`
