### ISSUE TITLE
PMD: Intent Icon Utility has a non private constructor.

### ISSUE THREAD

**Issue by whonamra** [rilling/OpenTracks-Concordia#472]
**Describe the technical debt**
Intent Utility class has non private constructor.

**Type of technical debt**
Code Smell.

**Location**
/src/main/java/de/dennisguse/opentracks/util/IntentUtils.java:34

**To Reproduce**

```
public class IntentUtils {

    private static final String TAG = IntentUtils.class.getSimpleName();

    private static final String JPEG_EXTENSION = "jpeg";

```

**Expected Solution**
Creating Intent Utils class' constructor.

**Comment by NithinHarikrishnan** [comment]
Intent Utils class constructor has been created.
![Screenshot 2023-04-16 204852](https://user-images.githubusercontent.com/123891802/232354169-503bf0e3-1801-4318-a472-597faa36461a.png)
