### ISSUE TITLE
Adding calories burnt

### ISSUE THREAD

**Issue by rilling** [rilling/OpenTracks-Concordia#6]
**Is your feature request related to a problem? Please describe.**
OpenTrack is currently not computing the calories burnt for a workout. While these calculations might be somewhat inaccurate they should be provided

**Describe the solution you'd like**
There a different formulas available on how to calculate the calories burnt per work out - depending on the type of exercise. The challenge is to come up with some adjustment factors, since not all the information might be readily available. E.g., power generated during the exercise, heart rate might be missing. However, we do have factors such as speed, duration and exercise type.
![Screenshot_20230130-184822](https://user-images.githubusercontent.com/1248571/215880476-27167eb9-0635-458d-8a9f-5d72e5e6a56f.png)

A sample record is provided. The calculation should provide an estimated calories burnt somewhere in the range of 260-280 Calories

Again, the file name will have to be renamed to be .gpx before importing it in OpenTrack
[2023-01-26_14_43_49.785_2023-01-26T14_43-05.txt](https://github.com/rilling/OpenTracks-Concordia/files/10550884/2023-01-26_14_43_49.785_2023-01-26T14_43-05.txt)

**Describe alternatives you've considered**
Various formulas should be available, they should consider ideally different criteria, such as type of exercise, age, weight, distance, elevation(?), speed 

**Additional context**

**Comment by plsakr** [comment]
Group 2 will add a utility method to convert calories to kjoules
