### ISSUE TITLE
src/main/java/de/dennisguse/opentracks/publicapi -> naming convention for variables

### ISSUE THREAD

**Issue by sanvinoth** [rilling/OpenTracks-Concordia#76]
**Describe the technical debt**
Naming convention for variables

**Type of technical debt**
Minor code smell

**Location**
src/main/java/de/dennisguse/opentracks/publicapi

**To Reproduce**

    private final String TAG = AbstractAPIActivity.class.getSimpleName();

to

    private final String activity = AbstractAPIActivity.class.getSimpleName();

If applicable:
![before](https://user-images.githubusercontent.com/45181379/216782424-8272d16a-659d-4a34-b0b3-0fddeda22eab.png)
![after](https://user-images.githubusercontent.com/45181379/216782433-afe4af22-8498-4535-b343-dbcd2df258c4.png)
![code](https://user-images.githubusercontent.com/45181379/216782468-bfb6b55d-d2d3-4acd-be1e-4a67af450dfe.png)

**Expected Solution**
Change variable name from TAG to activity following naming convention

**Comment by yusufkhan07** [comment]
Hi, I had to delete your commits because the build was failing (Not necessarily because of your commit but I had to delete all commits from the last 1 hour). Please commit your changes to the main branch again and make sure the build is working before committing.

**Comment by sanvinoth** [comment]
Commit Link : https://github.com/rilling/OpenTracks-Concordia/commit/f80c38b70b637250980008d8372bddb9ca306ca3
