### ISSUE TITLE
Adding comments and handling exceptions for undefined method

### ISSUE THREAD

**Issue by pankajdeep** [rilling/OpenTracks-Concordia#77]
**Describe the technical debt**
Add a nested comment explaining why this method is empty, throw an UnsupportedOperationException or complete the implementation.

**Type of technical debt**
Code Smell

**Location**
/src/main/java/de/dennisguse/opentracks/settings/SettingsCustomLayoutEditActivity.java

**To Reproduce**
![Screenshot (262)](https://user-images.githubusercontent.com/41828185/216784348-561e1652-68e9-4cbb-a6c7-61aa29236939.png)

**Expected Solution**
 - OpenTracks version: v4.2.1
 - Expected Resolution : Add Java Doc Comment explaining why the method is empty and throw an UnsupportedOperationException.

**Comment by yusufkhan07** [comment]
Hi, I had to delete your commits because the build was failing (Not necessarily because of your commit but I had to delete all commits from the last 1 hour). Please commit your changes to the main branch again and make sure build is working before committing.

**Comment by RancyKaur** [comment]
c
