### ISSUE TITLE
Correct one of the identical sub-expressions on both sides of operator "&&"

### ISSUE THREAD

**Issue by garvitkataria** [rilling/OpenTracks-Concordia#80]
## Describe the technical debt
The code analysis tool SonarQube has reported a bug regarding identical sub-expressions on both sides of an operator "&&". This issue is raised to fix a major code bug and fix TrackStatistics.java Class. 

### Type of technical debt
Bug

### Location
[src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java](https://github.com/rilling/OpenTracks-Concordia/blob/main/src/main/java/de/dennisguse/opentracks/stats/TrackStatistics.java)

### To Reproduce

_- Bug in Sonarqube_
![Screenshot 2023-02-04 at 1 48 11 PM](https://user-images.githubusercontent.com/23002147/216784750-e1dec910-70b5-4029-a5ba-4bc8d87fa713.png)

_- Screenshot from the class (TrackStatistics.java)_
![Screenshot 2023-02-04 at 2 01 57 PM](https://user-images.githubusercontent.com/23002147/216784946-847eccf5-ee0a-413d-87aa-878e4b875b63.png)

Expected Solution

OpenTracks version: v4.2.1
Expected Resolution: Remove one of the identical sub-expressions.

**Comment by garvitkataria** [comment]
Resolved the issue by removing one of the identical sub-expression - verified using SonarQube.
![Screenshot 2023-02-04 at 2 16 55 PM](https://user-images.githubusercontent.com/23002147/216785660-cdbcb33d-b188-4811-883e-4aa3740fc9a5.png)

**Comment by yusufkhan07** [comment]
I had to delete your commits because the build was failing (Not necessarily because of your commit but I had to delete all commits from the last 1 hour). Please commit your changes to the main branch again and make sure build is working before committing.
