### ISSUE TITLE
Complete the task associated to this TODO comment

### ISSUE THREAD

**Issue by bajwa96** [rilling/OpenTracks-Concordia#88]
Todo:// tags are commonly used to mark places where some more code is required, but which the developer wants to implement later.

Sometimes the developer will not have the time or will simply forget to get back to that tag.

This rule is meant to track those tags and to ensure that they do not go unnoticed.
Type of technical debt
1. SComplete the task associated to this TODO comment.

**Location**
1. src/main/java/de/dennisguse/opentracks/ui/customRecordingLayout/SettingsCustomLayoutEditAdapter.java

**To Reproduce**

1. This is a todo: so no need to reproduce

**Expected Solution**
 - R&D on the todo comment see if this is feasible 
 - remove todo if no longer needed

**Comment by karmakarvishal** [comment]
For now, the app is working fine so, for now, I am removing the to-do.
