### ISSUE TITLE
Define and throw a dedicated exception instead of using a generic one

### ISSUE THREAD

**Issue by swapy-S** [rilling/OpenTracks-Concordia#95]
**Describe the technical debt**
Define and throw a dedicated exception instead of using a generic one.

**Type of technical debt**
4 code smells containing Exception Handling

**Location**
OpenTracks-Concordia/src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java

**To Reproduce**

<img width="864" alt="4_code_smell" src="https://user-images.githubusercontent.com/50835521/216788859-095cf074-28ed-4336-a88e-f7f85e9a331b.png">

**Expected Solution**
- General runtime exception changed to _IllegalArgumentException_ and also created a _private static_ variable named "illegalArgument" which stores value "Not implemented". This variable is passed as an argument exception in the _IllegalArgumentException_.

**Fixed Code**
<img width="499" alt="Screenshot 2023-02-03 at 11 01 59 PM" src="https://user-images.githubusercontent.com/50835521/216788970-e87211d1-d66e-46fd-afb8-12a589adae91.png">
<img width="664" alt="Screenshot 2023-02-03 at 11 03 01 PM" src="https://user-images.githubusercontent.com/50835521/216788981-994b8c9a-d4e0-43b8-a5b8-569c9c242f81.png">

**Comment by RancyKaur** [comment]
Closing
