### ISSUE TITLE
Add the missing @deprecated Javadoc tag

### ISSUE THREAD

**Issue by swapy-S** [rilling/OpenTracks-Concordia#96]
**Describe the technical debt**
Add the missing @deprecated Javadoc tag

**Type of technical debt**
Code Smell containing javadoc warning. 

**Location**
OpenTracks-Concordia/src/main/java/de/dennisguse/opentracks/settings/PreferencesUtils.java

**To Reproduce**

<img width="861" alt="Screenshot 2023-02-03 at 10 59 30 PM" src="https://user-images.githubusercontent.com/50835521/216789188-a5300817-0839-40fc-b865-316c1167ed6a.png">

**Expected Solution**
- Inserted _@deprecated_ javadoc tag above the function.
- Added default argument in _@Deprecated_ annotation.

**Fixed Code**
<img width="425" alt="Screenshot 2023-02-03 at 11 11 44 PM" src="https://user-images.githubusercontent.com/50835521/216789261-4c68d6ca-953c-4303-b314-ea7cfbcfb250.png">

**Comment by RancyKaur** [comment]
Closing
